# The URL the site will be built for
base_url = "https://hatchling13.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "Hatchery"
description = "I couldn't help it"
theme = "hyde"

[extra]
hyde_links = [
    {url = "https://twitter.com/hatchling_13", name = "Twitter"},
    {url = "https://github.com/hatchling13", name = "Github"},
]